### ISSUE TITLE
文字入力フィールドを消せない

### ISSUE THREAD

**Issue by tzwada** [masm11/gpicann#3]
一旦画面に出してしまった文字入力フィールドが消せません。
そのため、テキストモードで画面を不意にクリックすると、その分文字入力フィールドが作られます。
そうなると、目的のテキストフィールドをマウスで選択することがほぼ不可能になってしまいます。（そのせいか、Raspiがフリーズしてしまいました）

空のフィールドは自動消去してほしいです。

**Comment by masm11** [comment]
@tzwada 
テキストも、選択して backspace で消すことができます。
空のテキストであっても消せます。

が、空のテキストは存在する意味がないので、自動消去するようにします。

**Comment by tzwada** [comment]
backspaceで消せたのですね。
確認しました。
