### ISSUE TITLE
テキストサイズを変更できない

### ISSUE THREAD

**Issue by tzwada** [masm11/gpicann#4]
テキストサイズを変更すると、入力対象がテキストサイズエリアから離れなくなります。
そのため、テキストフィールドに入力できなくなります。

**Comment by masm11** [comment]
@tzwada 修正しました。

ちなみに、その数字は線の太さです。テキストサイズは `Sans Regular 24` と表示されているボタンで変更できます。

**Comment by tzwada** [comment]
数字は先の太さだったのですね。なるほど。
[-][+]で変更しても問題なくテキスト入力などできることを確認しました。
