### ISSUE TITLE
テキストの視認性を改善して欲しい

### ISSUE THREAD

**Issue by tzwada** [masm11/gpicann#5]
テキスト表示ですが、Skitchのように白縁のアウトライン + ドロップシャドウとしてもらいたいです。
視認性が全然違うので。

**Comment by tzwada** [comment]
# 現状のテキスト
![text-field](https://user-images.githubusercontent.com/7919609/76492740-4bdd4e00-6474-11ea-80d6-59348da1c790.png)

**Comment by masm11** [comment]
アウトラインと影を付けてみました。

![with-outline](https://user-images.githubusercontent.com/7226237/76530941-ca0f1400-64b7-11ea-8713-522ffd0de661.png)

いかがでしょうか? かなり良くはなったと思うのですが、Skitch には及ばないですかね。

**Comment by masm11** [comment]
影が薄くなってますね。その辺もう少し修正してみます。

**Comment by masm11** [comment]
テキストの影を修正しました。また、デフォルトを Bold フォントにしました。

![test](https://user-images.githubusercontent.com/7226237/76632283-57209e80-6586-11ea-8f72-acfd58b80c9e.png)

見た目はとても改善してると思います。ただ、処理が重いかもしれません。Raspberry Pi で問題ないかご確認いただければと思います。

**Comment by tzwada** [comment]
これはよさげです！実機での確認してみます！

**Comment by tzwada** [comment]
バッチリと思います。対応ありがとう。
