### ISSUE TITLE
[FEATURE] Add button to copy image to clipboard

### ISSUE THREAD

**Issue by antonio-guillen** [masm11/gpicann#8]
This type of editor is common to use to make quick annotations on screenshots to share them in other applications such as mail, slack, teams or similar.

Having a button that allows you to copy the edited image to the clipboard would be great to be able to share the image quickly without having to save the file and later load it in the destination application.

**Comment by masm11** [comment]
Thank you for the nice feature request.

I'm busy recently and for a while.  I'll implement it after that.

**Comment by antonio-guillen** [comment]
Thanks to you, the extension is great.

The [screenshot-tool](https://extensions.gnome.org/extension/1112/screenshot-tool/) and [gpicann](https://github.com/masm11/gpicann/) is the perfect combination to replace [Shutter](https://shutter-project.org/) in Wayland environments :D

![image](https://user-images.githubusercontent.com/726710/125643191-6850ddac-7eea-4618-8dfa-e8a7029a07c7.png)

**Comment by angeles-ricardo-89** [comment]
I have open a pull-request which addresses this feature, waiting for the maintainer to accept it.

**Comment by masm11** [comment]
The PR is merged.  Please try it.

**Comment by antonio-guillen** [comment]
It works great!
